### ISSUE TITLE
Prototype of the new FS implementation using capnp flist and Node interface

### ISSUE THREAD

**Issue by zaibon** [g8os/fs#25]
Goal is 
- See if we can have performance gain by rewriting fs using the node interface of https://github.com/hanwen/go-fuse and using the new [flist capnpn format](https://github.com/Jumpscale/jumpscale_core8/blob/8.1.0_cleanup/lib/JumpScale/tools/flist/model.capnp)
- Do a small benchmark to compare path and node interface.

This task is not about rewriting completely fs now. we need more info about pudge before going there.

**Comment by iwanbk** [comment]
I implemented a simple loopback filesystem using node interface in https://gist.github.com/iwanbk/e691251c3057243a159beca4e60ff861

It is basically node version of https://github.com/hanwen/go-fuse/tree/master/example/loopback which use path interface.

In my tests, **path version was surprisingly 2x-3x faster than node version**.
my tests:
- download ubuntu.iso image from localhost
- copy the iso
- `cat the_iso > /dev/null`

i also did `dd` test with `dd if=/dev/zero of=test bs=1M count=1024 fconv=sync` command, but i doubt that the result is valid.

I don't include test results here because i think it is still in very early stage, there might be many changes in the future.

**Comment by iwanbk** [comment]
i update previous comment about test result, marked it as invalid results

**Comment by iwanbk** [comment]
I did two kind of tests:
(1) read-write operation on big file
the result is similar, i think it is because loopback pathfs and nodefs use same underlying mechanism (use host filesystem)

(2) read-write operation on many small files
I did two tests:
- copy all my code under `$GOPATH/src/bitbucket.org` to fuse, and then copy it from fuse to host filesystem
- copy root filesystem of docker container to fuse and then copy it from fuse to host filesystem

nodefs give better performance, sometimes it reached 2x than pathfs.
I think it is because pathfs do many operations to translate from `path` to `inode`

detailed results:
node  bitbucket
```
#time cp -a ~/pathgo/src/bitbucket.org .

real	4m41.586s
user	0m0.130s
sys	0m33.220s

# time cp -a bitbucket.org /tmp/

real	2m2.055s
user	0m0.460s
sys	0m3.280s
```
path bitbucket
```
#time cp -a ~/pathgo/src/bitbucket.org .

real	6m53.270s
user	0m0.070s
sys	0m31.920s

# time cp -a bitbucket.org /tmp/

real	3m45.586s
user	0m0.210s
sys	0m4.370s
```

node docker
```
u# time cp -a ~/pathgo/buntu . && time cp -a buntu /tmp/

real	3m38.257s
user	0m0.090s
sys	0m37.330s

real	3m8.929s
user	0m0.490s
sys	0m5.550s
```
path docker
```
real	6m28.152s
user	0m0.120s
sys	0m36.700s

# time cp -a buntu /tmp/

real	5m25.176s
user	0m0.230s
sys	0m6.370s
```

**Comment by iwanbk** [comment]
```
See if we can have performance gain by rewriting fs using the node interface of https://github.com/hanwen/go-fuse and using the new flist capnpn format
```
About performance, i think we can get it.

But i'm not sure about the correctness of the `new flist capnp` format.
If we want to use node interface and compatible with posix interface, i think it is better if we use inode model, instead of inventing our own model.

By looking at the model, i don't know how we will create model for hard link
