### ISSUE TITLE
touchDeleted  executed without waiting for actual file operation to succeed

### ISSUE THREAD

**Issue by iwanbk** [g8os/fs#9]
happens in fsDir.Rename & fsDir.Remove

**Comment by muhamadazmy** [comment]
This is not a valid issue, the touchDelete in both functions is called "before" the method returns. Which means the function body is already executed. But we don't care if the delete or the remove operation on the actual file succeeded or not because the file itself may not exits. 

it happens if you are trying to rename/remove a file that wasn't downloaded yet from the stor (you never tried to access the file itself)

**Comment by iwanbk** [comment]
@muhamadazmy 
Thanks, i understand.

But, is it also OK to call `touchDelete` **after** delete/remove succeed?

**Comment by muhamadazmy** [comment]
it happens in all cases (success or error of deleting of actual file)
